### ISSUE TITLE
How to use the javascript library with OpenLayers ?

### ISSUE THREAD

**Issue by samtux** [terrestris/geostyler-openlayers-parser#58]
I want to review and test the library in OpenLayers 4.x, but I haven't been able to understand how it works. Could you please share the instructions to define a Style in the form of GeoStyler and then convert it into OpenLayers styles?

I think it's an interesting project, but with limited documentation.

Thanks!!!

**Comment by KaiVolland** [comment]
Hey @samtux, nice to see that you`re interested.

You're right. The documentation is very limited. :)

But the implementation is very easy. 

Just import the library. You can then use the  `readStyle` and `writeStyle` methods.

If you want to use the parser directly inside your html document you still need to install it via npm (memo to me: we should think about this). There you'll find a browser folder. You can use the there found script just as every other Javascript.

If you want to have some examples you can look at the `OlStyleParser.spec.ts` (typescript is not required to use the lib). 

BTW: Just writing this from my phone so apologizes for every typo.

**Comment by KaiVolland** [comment]
... in case of the browser you can use the methods via: `GeoStylerOpenlayersParser.readStyle` or `GeoStylerOpenlayersParser. writeStyle`.

**Comment by samtux** [comment]
Thank you @KaiVolland  for the help in using the GeoStyler library.  I managed to build the library with the versions of nodejs v10.13.0 and npm v6.4.1 and the following commands:

```bash
> npm install 
> npm run build
```

Here is the website where I uploaded the library to test it: [https://geoestyler.netlify.com/](https://geoestyler.netlify.com/)

Using directly the olStyleParser.js library, I have tried using the methods but in the following way:

```javascript
var geostyle = {
  "name": "Style Points",
  "rules": [
    {
      "name": "Rule 1",
      "symbolizers": [
        {
          "kind": "Icon",
          "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Parking_icon.svg/128px-Parking_icon.svg.png",
          "size": 10
        }
      ]
    }
  ]
};

var GeoStyle = new GeoStylerOpenlayersParser.OlStyleParser;

GeoStyle.writeStyle(geostyle).then(function(sty) {
	var style =  new ol.style.Style( sty );
        vectorLayer.getSource().getFeatures().forEach(function(feature){       		
              feature.setStyle( style );
        });
});
```

I have also tried to use the readStyle method and always with the same error:

```javascript
var sty = vectorLayer.getStyle();

GeoStyle.readStyle(sty).then(function(data) {
     console.log(data)
})
```

```javascript
Uncaught (in promise) Error: StyleType could not be detected
    at t.getStyleTypeFromOlStyle (olStyleParser.js:1)
    at olStyleParser.js:1
    at Array.forEach (<anonymous>)
    at t.getSymbolizersFromOlStyle (olStyleParser.js:1)
    at t.getRuleFromOlStyle (olStyleParser.js:1)
    at t.olStyleToGeoStylerStyle (olStyleParser.js:1)
    at olStyleParser.js:1
    at new Promise (<anonymous>)
    at t.readStyle (olStyleParser.js:1)
    at <anonymous>:1:10
```

I don't know if I'm doing something wrong, and if the library should directly use the readStyle and writeStyle methods or should be done through Javascript Promises.

Thank you.

**Comment by samtux** [comment]
Hi @KaiVolland, I couldn't use the geostyler-openlayers-parser library.  However, exploring the syntax of GeoStyler is really amazing. I like the ease as you can define all the symbology in a javascript object.  For the following example, I adapted some code to show some icons and texts using the syntax of GeoStyler.

http://plnkr.co/edit/7gMJo66flp5YNETenvEJ?p=preview

Great work with this excellent tool.

**Comment by KaiVolland** [comment]
Sorry for the delayed reply.

To receive faster support you may want to open further issues in the main repository https://github.com/terrestris/geostyler/issues as we manage them there https://github.com/terrestris/geostyler/projects. To be honest i thought i disabled issues in the parser allready.

No back to topic:

Your approach in the first comment was very close. But the `writeStyle` method allready returns an `ol.style.Style`.

I'd also recommend to set the style on the layer and not at the feature. This might also be the reason why the `readyStyle` function fails.

Maybe try this for `writeStyle`:

```js
GeoStyle.writeStyle(geostyle)
  .then(function(style) {
    vectorLayer.setStyle(style);
  });
```
... the `readSyle` should work afterwards.

I forked and modified your plunker. I modified `scripts.js` to only contain the geostyler-style and the `index.html` to use the parser: https://plnkr.co/edit/OVP3p2sN7F3i8eyHNF3t?p=preview

A very important (and not documented :man_facepalming: ) part is that you add your `ol` global to the parser constructor when using the implementation for the browser.

**Comment by chrismayer** [comment]
> A very important (and not documented :man_facepalming:  ) part is that you add your ol global to the parser constructor when using the implementation for the browser.

```javascript
cont olParser = new GeoStylerOpenlayersParser.OlStyleParser(ol);
```

**Comment by samtux** [comment]
Hi @KaiVolland, I really appreciate your help and explanation. I will follow your recommendations to write to the main repository. 

Interesting project, it would be interesting if GeoStyler syntax is an open standard analogous to SLD.
